"""
Agentic AI Data Analyst - Natural language dataframe querying
"""

import streamlit as st
import pandas as pd
import numpy as np
import io
import time
from utils.theme import inject_tailwind, page_header, COLORS
from utils.components import section_header, info_banner
from utils.data_loader import load_data
from utils.llm import _get_api_key
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_experimental.agents import create_pandas_dataframe_agent

st.set_page_config(page_title="AI Data Analyst", page_icon="🤖", layout="wide")
inject_tailwind()

page_header("AI Data Analyst", "Ask complex questions in plain english. The AI will write and execute data analysis code to find the answer.", "robot")

# App State
if "messages" not in st.session_state:
    st.session_state.messages = []
if "agent" not in st.session_state:
    st.session_state.agent = None

api_key = _get_api_key()

if not api_key:
    info_banner("⚠️ A valid GEMINI_API_KEY is required to use the Agentic LLM features.", "warning")
    st.stop()

df = load_data()

# Initialize Langchain Pandas Agent
try:
    if st.session_state.agent is None:
        llm = ChatGoogleGenerativeAI(
            model="gemini-2.5-flash",
            google_api_key=api_key,
            temperature=0.0
        )
        
        st.session_state.agent = create_pandas_dataframe_agent(
            llm,
            df,
            verbose=False,
            allow_dangerous_code=True,
            agent_type="tool-calling",
            return_intermediate_steps=True,
            prefix=(
                "You are an AI Data Scientist analyzing a U.S. Food Insecurity dataset. "
                "The dataset is loaded as a pandas DataFrame named `df`. "
                "You MUST use the python_repl_ast tool to execute pandas code and answer the user's question. "
                "Never guess or return a final answer without running code first to calculate it. "
                "When formatting your final answer, use markdown."
            )
        )
except Exception as e:
    st.error(f"Failed to initialize AI Agent: {e}")
    st.stop()

col1, col2 = st.columns([3, 1])

with col1:
    st.markdown('<div class="bg-gray-50 border border-gray-200 rounded-xl p-6 min-h-[500px]">', unsafe_allow_html=True)
    
    # Render chat history
    for msg in st.session_state.messages:
        with st.chat_message(msg["role"], avatar="🤖" if msg["role"] == "assistant" else "👤"):
            st.markdown(msg["content"])
            if "code" in msg:
                with st.expander("Show AI-Generated Code"):
                    st.code(msg["code"], language="python")

    # Chat input
    if prompt := st.chat_input("E.g., Which 5 counties in Texas saw the highest spike in child food insecurity between 2019 and 2021?"):
        # Append user message
        st.session_state.messages.append({"role": "user", "content": prompt})
        with st.chat_message("user", avatar="👤"):
            st.markdown(prompt)

        # Generate response
        with st.chat_message("assistant", avatar="🤖"):
            placeholder = st.empty()
            placeholder.markdown(f'<i class="fas fa-circle-notch fa-spin text-blue-500 mr-2"></i> Analyzing {len(df):,} rows of data...', unsafe_allow_html=True)
            
            try:
                # Send message to model
                response = st.session_state.agent.invoke({"input": prompt})
                
                # Extract code snippets if tool was used
                executed_code = ""
                intermediate_steps = response.get("intermediate_steps", [])
                for action, observation in intermediate_steps:
                    # action.tool_input handles the python code string generated by the agent
                    code_val = action.tool_input
                    if isinstance(code_val, dict) and 'query' in code_val:
                        code_val = code_val['query']
                    executed_code += f"# Code Executed by AI:\n{code_val}\n\n"
                    executed_code += f"# Result:\n{observation}\n\n"

                final_answer = response.get("output", "")
                placeholder.markdown(final_answer)
                
                if executed_code:
                    with st.expander("Show AI-Generated Code"):
                        st.code(executed_code, language="python")
                
                # Save assistant response
                st.session_state.messages.append({
                    "role": "assistant", 
                    "content": final_answer,
                    "code": executed_code if executed_code else None
                })
                
            except Exception as e:
                placeholder.error(f"Agent Execution Error: {e}")

    st.markdown('</div>', unsafe_allow_html=True)

with col2:
    st.markdown(
        """
        <div class="bg-blue-50 rounded-xl p-5 border border-blue-100 shadow-sm">
            <h3 class="text-blue-800 font-bold text-sm mb-3">
                <i class="fas fa-lightbulb text-yellow-500 mr-2"></i>How this works
            </h3>
            <p class="text-sm text-blue-900 leading-relaxed mb-4">
                This isn't a standard chatbot. It is an <b>Agentic Code Execution Engine</b> powered by Gemini 2.5 Flash.
            </p>
            <p class="text-sm text-blue-900 leading-relaxed mb-4">
                When you ask a question, the AI won't guess the answer or regurgitate its training data. Instead, it will <b>write custom Python Pandas code</b>, securely execute that code against the live <code>Dataframe</code> backing this dashboard, and synthesize the mathematical outputs into a precise answer.
            </p>
            <h4 class="text-xs font-bold text-blue-800 uppercase tracking-wider mb-2 mt-4">Example Questions</h4>
            <ul class="text-sm text-blue-900 space-y-3">
                <li class="bg-white p-2 rounded border border-blue-200 shadow-sm font-medium">Which state had the largest <b>decrease</b> in child food insecurity between 2012 and 2022?</li>
                <li class="bg-white p-2 rounded border border-blue-200 shadow-sm font-medium">What is the average poverty rate and cost per meal for the 10 counties with the highest overall food insecurity in 2023?</li>
                <li class="bg-white p-2 rounded border border-blue-200 shadow-sm font-medium">List the top 5 'Rural' counties with the lowest unemployment rate but highest SNAP participation.</li>
            </ul>
        </div>
        """, unsafe_allow_html=True
    )
