---
title: "Misc Functions"
author: "Ryann Tompkins"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(tidyverse)
```

```{r}
fa_pre <- read_excel("../data/feeding_america(2009-2018).xlsx")
fa_post<- read_excel("../data/feeding_america(2019-2023).xlsx")

intersect(names(fa_pre),names(fa_post))
```


# Year over year change plot
```{r}

fi_change_plot <- function(
  year_start, year_end,
  variable,
  plot_type = "Slope"
) {
   df <- food_data %>%
    filter(year %in% c(year_start, year_end)) %>%
    select(fips, year, value = all_of(variable)) %>%
    tidyr::pivot_wider(
      names_from = year,
      values_from = value,
      names_prefix = "year_"
    ) %>%
    mutate(
      change = .data[[paste0("year_", year_end)]] -
               .data[[paste0("year_", year_start)]]
    ) %>%
    drop_na(change)

  if (plot_type == "Slope") {
    p <- df %>%
      slice_max(abs(change), n = 30) |> 
      tidyr::pivot_longer(cols = c(value_start, value_end),
                          names_to = "year", values_to = "value") |> 
      mutate(year = recode(year,
                           "value_start" = year_start,
                           "value_end" = year_end)) |> 
      ggplot(aes(x = year, y = value, group = fips)) +
      geom_line(alpha = 0.5) +
      geom_point(size = 2) +
      labs(
        title = paste(variable, "Change:", year_start, "→", year_end),
        y = "Value",
        x = "Year"
      )

  } else if (plot_type == "Histogram") {
    p <- ggplot(df, aes(x = change)) +
      geom_histogram(bins = 30, fill = "steelblue") +
      labs(
        title = paste("Distribution of Change", year_start, "→", year_end),
        x = "Change"
      )

  } else if (plot_type == "Bar Top N") {
    p <- df |> 
      slice_max(abs(change), n = 20) |> 
      ggplot(aes(x = reorder(FIPS, change), y = change)) +
      geom_col(fill = "darkgreen") +
      coord_flip() +
      labs(
        title = paste("Largest Changes in", variable),
        y = "Change"
      )
  }

  return(p + theme_minimal())
}
```


Potential UI
```{r}
ui <- fluidPage(

  titlePanel("Year-over-Year Food Insecurity Change"),

  sidebarLayout(

    sidebarPanel(

      selectInput(
        "year_start",
        "Start Year:",
        choices = 2009:2023,
        selected = "2018"
      ),

      selectInput(
        "year_end",
        "End Year:",
        choices = 2009:2023,
        selected = "2023"
      ),

      selectInput(
        "variable",
        "Variable:",
        choices = c(
          "Overall Food Insecurity Rate",
          "Child Food Insecurity Rate",
          "povert_rate",
          "No of Food Insecure Persons Overall",
          "Cost Per Meal"
        ),
        selected = "Overall Food Insecurity Rate"
      ),

      selectInput(
        "plot_type",
        "Plot Type:",
        choices = c("Slope", "Histogram", "Bar Top N"),
        selected = "Slope"
      )
    ),


    mainPanel(
      plotOutput("change_plot")
    )
  )
)
```


Potantial Server
```{r}
server <- function(input, output, session) {

  output$change_plot <- renderPlot({

    fi_change_plot(
      year_start = input$year_start,
      year_end   = input$year_end,
      variable   = input$variable,
      plot_type  = input$plot_type
    )

  })

}
```


# Now Plot for Race Differences (2019-2023 Only)
```{r}
race_gap_plot <- function(
  year_input,
  race_target,
  compare_group,
  plot_type = "Histogram"
){

  df <- fa_post |> 
    filter(year == year_input) |> 
    select(
      fips,
      race_target_value = all_of(race_target),
      compare_value     = all_of(compare_group)
    ) 
  df <- df |>
  drop_na(race_target_value, compare_value) |> 
    mutate(
      race_gap = race_target_value - compare_value
    )


  if (plot_type == "Histogram") {

    p <- ggplot(df, aes(x = race_gap)) +
      geom_histogram(bins = 30) +
      labs(
        title = paste("Difference:", race_target, " - ", compare_group,
                      " (", year_input, ")"),
        x = "Difference"
      )

  } else if (plot_type == "Boxplot") {

    p <- df %>% 
      ggplot(aes(y = race_gap)) +
      geom_boxplot() +
      labs(
        title = paste("Boxplot:", race_target, " - ", compare_group,
                      " (", year_input, ")"),
        y = "Difference"
      )

  } else if (plot_type == "Top N") {

    p <- df |> 
      slice_max(abs(race_gap), n = 20) |>
      ggplot(aes(x = reorder(fips, race_gap), y = race_gap)) +
      geom_col() +
      coord_flip() +
      labs(
        title = paste("Top 20:", race_target, " - ", compare_group,
                      " (", year_input, ")"),
        y = "Difference"
      )
  }

  return(p + theme_minimal())
}


```

Potential UI
```{r}
selectInput(
  "year_race",
  "Year:",
  choices = 2019:2023,
  selected = 2023
)

selectInput(
  "race_target",
  "Race:",
  choices = c("Food Insecurity Rate among Black Persons (all ethnicities)",
              "Food Insecurity Rate among Hispanic Persons (any race)",
              "Food Insecurity Rate among White, non-Hispanic Persons"),
  selected = "Food Insecurity Rate among Black Persons (all ethnicities)"
)

selectInput(
  "compare_group",
  "Compare To:",
  choices = c(
              "Food Insecurity Rate among Black Persons (all ethnicities)",
              "Food Insecurity Rate among Hispanic Persons (any race)",
              "Food Insecurity Rate among White, non-Hispanic Persons",
              "Overall Food Insecurity Rate" ),
  selected = "Overall Food Insecurity Rate"
)

selectInput(
  "plot_type_race",
  "Plot Type:",
  choices = c("Histogram","Boxplot","Top N"),
  selected = "Histogram"
)
```

Potential Server
```{r}
output$race_plot <- renderPlot({

  race_gap_plot(
    year_input    = input$year_race,
    race_target   = input$race_target,
    compare_group = input$compare_group,
    plot_type     = input$plot_type_race
  )

})
```
