---
title: "Graph Functions"
author: "Ryann Tompkins"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(dplyr)

```


Big Function for Graphs
```{r}
#Converting data set to years
mmg_list <- list(
  "2009" = MMG_2009,
  "2010" = MMG_2010,
  "2011" = MMG_2011,
  "2012" = MMG_2012,
  "2013" = MMG_2013,
  "2014" = MMG_2014,
  "2015" = MMG_2015,
  "2016" = MMG_2016,
  "2017" = MMG_2017,
  "2018" = MMG_2018,
  "2019" = MMG_2019,
  "2020" = MMG_2020,
  "2021" = MMG_2021,
  "2022" = MMG_2022,
  "2023" = MMG_2023
)

mmg_plot <- function(year_input, variable, plot_type, data_list = mmg_list) {
  
  df <- data_list[[as.character(year_input)]]
  
  if(!variable %in% names(df)) stop("Variable not found in dataset.")
  
  p <- ggplot(df, aes(x = .data[[variable]]))
  
  if (plot_type == "Histogram") {
    p <- p +
      geom_histogram(bins = 30, fill = "steelblue", color = "white") +
      labs(title = paste(variable, "-", year_input),
           x = variable,
           y = "Count")
    
  } else if (plot_type == "Boxplot") {
    p <- ggplot(df, aes(y = .data[[variable]])) +
      geom_boxplot(fill = "orange", alpha = 0.7) +
      labs(title = paste(variable, "-", year_input),
           y = variable)
    
  } else if (plot_type == "Density Plot") {
    p <- p +
      geom_density(fill = "purple", alpha = 0.4) +
      labs(title = paste(variable, "-", year_input),
           x = variable,
           y = "Density")
    
  } else {
    stop("Invalid plot type.")
  }
  
  return(p + theme_minimal())
}
```

Potential UI
```{r}
ui <- fluidPage(
  titlePanel("MMG Graph Explorer"),
  
  sidebarLayout(
    sidebarPanel(
      selectInput("year", "Select Year:",
                  choices = 2009:2023,
                  selected = 2020),
      
      selectInput("plot_type", "Plot Type:",
                  choices = c("Histogram", "Boxplot", "Density Plot")),
      
      uiOutput("var_select")   
    ),
    
    mainPanel(
      plotOutput("mmg_plot", height = "500px")
    )
  )
)
```

Server
```{r}
server <- function(input, output, session) {
  
  output$var_select <- renderUI({
    df <- mmg_list[[as.character(input$year)]]
    
    numeric_vars <- names(df)[sapply(df, is.numeric)]
    
    selectInput("variable", "Select Variable:", choices = numeric_vars)
  })
  
  output$mmg_plot <- renderPlot({
    req(input$variable)
    mmg_plot(
      year_input = input$year,
      variable = input$variable,
      plot_type = input$plot_type
    )
  })
}
```
